// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HttpResponse.proto

package com.tinysakura.xhaka.common.gateway.serialize.protobuf;

public final class HttpResponseOuterClass {
  private HttpResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HttpResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tinysakura.xhaka.common.gateway.serialize.protobuf.HttpResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    java.util.List<HeaderOuterClass.Header>
        getHeadersList();
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    HeaderOuterClass.Header getHeaders(int index);
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    int getHeadersCount();
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    java.util.List<? extends HeaderOuterClass.HeaderOrBuilder>
        getHeadersOrBuilderList();
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    HeaderOuterClass.HeaderOrBuilder getHeadersOrBuilder(
            int index);

    /**
     * <code>bytes body = 3;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code com.tinysakura.xhaka.common.gateway.serialize.protobuf.HttpResponse}
   */
  public  static final class HttpResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tinysakura.xhaka.common.gateway.serialize.protobuf.HttpResponse)
      HttpResponseOrBuilder {
    // Use HttpResponse.newBuilder() to construct.
    private HttpResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HttpResponse() {
      status_ = 0;
      headers_ = java.util.Collections.emptyList();
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HttpResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                headers_ = new java.util.ArrayList<HeaderOuterClass.Header>();
                mutable_bitField0_ |= 0x00000002;
              }
              headers_.add(
                  input.readMessage(HeaderOuterClass.Header.parser(), extensionRegistry));
              break;
            }
            case 26: {

              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          headers_ = java.util.Collections.unmodifiableList(headers_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HttpResponseOuterClass.internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HttpResponseOuterClass.internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HttpResponse.class, Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int HEADERS_FIELD_NUMBER = 2;
    private java.util.List<HeaderOuterClass.Header> headers_;
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    public java.util.List<HeaderOuterClass.Header> getHeadersList() {
      return headers_;
    }
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    public java.util.List<? extends HeaderOuterClass.HeaderOrBuilder>
        getHeadersOrBuilderList() {
      return headers_;
    }
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    public int getHeadersCount() {
      return headers_.size();
    }
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    public HeaderOuterClass.Header getHeaders(int index) {
      return headers_.get(index);
    }
    /**
     * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
     */
    public HeaderOuterClass.HeaderOrBuilder getHeadersOrBuilder(
        int index) {
      return headers_.get(index);
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 3;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      for (int i = 0; i < headers_.size(); i++) {
        output.writeMessage(2, headers_.get(i));
      }
      if (!body_.isEmpty()) {
        output.writeBytes(3, body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      for (int i = 0; i < headers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, headers_.get(i));
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, body_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HttpResponse)) {
        return super.equals(obj);
      }
      HttpResponse other = (HttpResponse) obj;

      boolean result = true;
      result = result && (getStatus()
          == other.getStatus());
      result = result && getHeadersList()
          .equals(other.getHeadersList());
      result = result && getBody()
          .equals(other.getBody());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      if (getHeadersCount() > 0) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + getHeadersList().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HttpResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HttpResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HttpResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HttpResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HttpResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HttpResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HttpResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HttpResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HttpResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HttpResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HttpResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tinysakura.xhaka.common.gateway.serialize.protobuf.HttpResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tinysakura.xhaka.common.gateway.serialize.protobuf.HttpResponse)
        HttpResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HttpResponseOuterClass.internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HttpResponseOuterClass.internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HttpResponse.class, Builder.class);
      }

      // Construct using com.tinysakura.xhaka.common.gateway.serialize.protobuf.HttpResponseOuterClass.HttpResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeadersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        if (headersBuilder_ == null) {
          headers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          headersBuilder_.clear();
        }
        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HttpResponseOuterClass.internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_descriptor;
      }

      public HttpResponse getDefaultInstanceForType() {
        return HttpResponse.getDefaultInstance();
      }

      public HttpResponse build() {
        HttpResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HttpResponse buildPartial() {
        HttpResponse result = new HttpResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.status_ = status_;
        if (headersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            headers_ = java.util.Collections.unmodifiableList(headers_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.headers_ = headers_;
        } else {
          result.headers_ = headersBuilder_.build();
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HttpResponse) {
          return mergeFrom((HttpResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HttpResponse other) {
        if (other == HttpResponse.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (headersBuilder_ == null) {
          if (!other.headers_.isEmpty()) {
            if (headers_.isEmpty()) {
              headers_ = other.headers_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureHeadersIsMutable();
              headers_.addAll(other.headers_);
            }
            onChanged();
          }
        } else {
          if (!other.headers_.isEmpty()) {
            if (headersBuilder_.isEmpty()) {
              headersBuilder_.dispose();
              headersBuilder_ = null;
              headers_ = other.headers_;
              bitField0_ = (bitField0_ & ~0x00000002);
              headersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeadersFieldBuilder() : null;
            } else {
              headersBuilder_.addAllMessages(other.headers_);
            }
          }
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HttpResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HttpResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <code>int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<HeaderOuterClass.Header> headers_ =
        java.util.Collections.emptyList();
      private void ensureHeadersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          headers_ = new java.util.ArrayList<HeaderOuterClass.Header>(headers_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          HeaderOuterClass.Header, HeaderOuterClass.Header.Builder, HeaderOuterClass.HeaderOrBuilder> headersBuilder_;

      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public java.util.List<HeaderOuterClass.Header> getHeadersList() {
        if (headersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(headers_);
        } else {
          return headersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public int getHeadersCount() {
        if (headersBuilder_ == null) {
          return headers_.size();
        } else {
          return headersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public HeaderOuterClass.Header getHeaders(int index) {
        if (headersBuilder_ == null) {
          return headers_.get(index);
        } else {
          return headersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder setHeaders(
          int index, HeaderOuterClass.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.set(index, value);
          onChanged();
        } else {
          headersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder setHeaders(
          int index, HeaderOuterClass.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.set(index, builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder addHeaders(HeaderOuterClass.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.add(value);
          onChanged();
        } else {
          headersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder addHeaders(
          int index, HeaderOuterClass.Header value) {
        if (headersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeadersIsMutable();
          headers_.add(index, value);
          onChanged();
        } else {
          headersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder addHeaders(
          HeaderOuterClass.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.add(builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder addHeaders(
          int index, HeaderOuterClass.Header.Builder builderForValue) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.add(index, builderForValue.build());
          onChanged();
        } else {
          headersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder addAllHeaders(
          Iterable<? extends HeaderOuterClass.Header> values) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, headers_);
          onChanged();
        } else {
          headersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder clearHeaders() {
        if (headersBuilder_ == null) {
          headers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          headersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public Builder removeHeaders(int index) {
        if (headersBuilder_ == null) {
          ensureHeadersIsMutable();
          headers_.remove(index);
          onChanged();
        } else {
          headersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public HeaderOuterClass.Header.Builder getHeadersBuilder(
          int index) {
        return getHeadersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public HeaderOuterClass.HeaderOrBuilder getHeadersOrBuilder(
          int index) {
        if (headersBuilder_ == null) {
          return headers_.get(index);  } else {
          return headersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public java.util.List<? extends HeaderOuterClass.HeaderOrBuilder>
           getHeadersOrBuilderList() {
        if (headersBuilder_ != null) {
          return headersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(headers_);
        }
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public HeaderOuterClass.Header.Builder addHeadersBuilder() {
        return getHeadersFieldBuilder().addBuilder(
            HeaderOuterClass.Header.getDefaultInstance());
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public HeaderOuterClass.Header.Builder addHeadersBuilder(
          int index) {
        return getHeadersFieldBuilder().addBuilder(
            index, HeaderOuterClass.Header.getDefaultInstance());
      }
      /**
       * <code>repeated .com.tinysakura.xhaka.common.gateway.serialize.protobuf.Header headers = 2;</code>
       */
      public java.util.List<HeaderOuterClass.Header.Builder>
           getHeadersBuilderList() {
        return getHeadersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          HeaderOuterClass.Header, HeaderOuterClass.Header.Builder, HeaderOuterClass.HeaderOrBuilder>
          getHeadersFieldBuilder() {
        if (headersBuilder_ == null) {
          headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              HeaderOuterClass.Header, HeaderOuterClass.Header.Builder, HeaderOuterClass.HeaderOrBuilder>(
                  headers_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          headers_ = null;
        }
        return headersBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 3;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 3;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 3;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.tinysakura.xhaka.common.gateway.serialize.protobuf.HttpResponse)
    }

    // @@protoc_insertion_point(class_scope:com.tinysakura.xhaka.common.gateway.serialize.protobuf.HttpResponse)
    private static final HttpResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HttpResponse();
    }

    public static HttpResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HttpResponse>
        PARSER = new com.google.protobuf.AbstractParser<HttpResponse>() {
      public HttpResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HttpResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HttpResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HttpResponse> getParserForType() {
      return PARSER;
    }

    public HttpResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022HttpResponse.proto\0226com.tinysakura.xha" +
      "ka.common.gateway.serialize.protobuf\032\014He" +
      "ader.proto\"}\n\014HttpResponse\022\016\n\006status\030\001 \001" +
      "(\005\022O\n\007headers\030\002 \003(\0132>.com.tinysakura.xha" +
      "ka.common.gateway.serialize.protobuf.Hea" +
      "der\022\014\n\004body\030\003 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          HeaderOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tinysakura_xhaka_common_gateway_serialize_protobuf_HttpResponse_descriptor,
        new String[] { "Status", "Headers", "Body", });
    HeaderOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
